version: "3.8"
services:
  postgresql:
    user: "1000"
    privileged: true
    container_name: postgresql-14
    image: bitnami/postgresql:14
    ports:
      - 5433:5432
    volumes:
      - "/opt/postgres:/bitnami/postgresql:rw"
    environment:
      POSTGRESQL_PASSWORD: flexdoc99
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: always