version: "3.9"

# EXECUTE O COMANDO ABAIXO ANTES DE RODAR ESTE DOCKER COMPOSER
# docker network create bancos-net
# docker network create flexdoc-net 

# COMANDO PARA RODAR ESTE COMPOSE
# docker-compose up -d --force-recreate

services:

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - "../volumes/postgres:/bitnami/postgresql"
    environment:
      POSTGRESQL_PASSWORD: flexdoc99
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

  # pdAdmin conecta o postgres do docker somente usando o host como "host.docker.internal"
  pgadmin:
    container_name: pgadmin-4
    image: dpage/pgadmin4
    ports:
      - 5454:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: flexdoc99
      PGADMIN_DEFAULT_EMAIL: user@email.com
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped

networks:
  bancos-net:
    external: true
  flexdoc-net:
    external: true
      
