version: "3.9"

# EXECUTE O COMANDO ABAIXO ANTES DE RODAR ESTE DOCKER COMPOSER
# docker network create bancos-net
# docker network create flexdoc-net 

# COMANDO PARA RODAR ESTE COMPOSE
# docker-compose up -d --force-recreate

services:
  mysql:
    container_name: mysql
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    volumes:
      - "./volumes/mysql:/bitnami/mysql"
      # - "./my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: flexdoc99
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - "./volumes/postgres:/bitnami/postgresql"
    environment:
      POSTGRESQL_PASSWORD: flexdoc99
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

  # pdAdmin conecta o postgres do docker somente usando o host como "host.docker.internal"
  pgadmin:
    container_name: pgadmin-4
    image: dpage/pgadmin4
    ports:
      - 5454:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: flexdoc99
      PGADMIN_DEFAULT_EMAIL: user@email.com
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - "./volumes/mongodb:/bitnami/mongodb"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: flexdoc99
      MONGODB_DATABASE: test
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - 17000:8081
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: flexdoc99
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

networks:
  bancos-net:
    external: true
  flexdoc-net:
    external: true
      
