version: "3.9"
#docker run -d --name mysql_vol -e ALLOW_EMPTY_PASSWORD=true -v E:\DESENV\docker\mysql\volume\data:/bitnami/mysql/data --network minha-rede -p 3307:3306 bitnami/mysql:latest 
#docker-compose up -d --force-recreate

services:

  mysql:
    container_name: MySql-5.7
    image: bitnami/mysql:5.7.37
    ports:
      - 3306:3306
    volumes:
      - 'volume_mysql:/bitnami/mysql'
      - './my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped

  postgresql:
    container_name: Postgresql-14
    image: bitnami/postgresql:14
    ports:
      - 5432:5432
    volumes:
      - 'volume_postgresql:/bitnami/postgresql'
    environment:
      POSTGRESQL_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  # pdAdmin conecta o postgres do docker somente usando o host como "host.docker.internal"
  pgadmin:
    container_name: PgAdmin-4
    image: dpage/pgadmin4
    ports:
      - 54321:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: user@email.com
    depends_on:
      postgresql:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    container_name: MongoDB
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - 'volume_mongodb:/bitnami/mongodb'
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
      MONGODB_DATABASE: test
    restart: unless-stopped

  mongo-express:
    container_name: Mongo-Express
    image: mongo-express:latest
    ports:
      - 17000:8081
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    restart: always

volumes:
  volume_mysql:
    driver: local
  volume_postgresql:
    driver: local
  volume_mongodb:
    driver: local
