apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: pgadmin-ns
data:
  PGADMIN_DEFAULT_EMAIL: admin@flexdoc.com.br
  PGADMIN_LISTEN_PORT: "5454"
  SCRIPT_NAME: /pgadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin-ns
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: ZmxleGRvYzk5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin     
      annotations:
        # anotacao apenas para alterar e fazer deploy sem alterar as configuraçoes
        image-version: 2022-09-13_1338
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          envFrom:
            - configMapRef:
                name: pgadmin-config
            - secretRef:
                name: pgadmin-secret
          ports:
            - containerPort: 5454
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: pgadmin-ns
spec:
  selector:
    app: pgadmin
  ports:
    - port: 5454