apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: pgadmin-ns
data:
  PGADMIN_DEFAULT_EMAIL: admin@flexdoc.com.br
  PGADMIN_LISTEN_PORT: "5454"
  SCRIPT_NAME: /pgadmin
  # PGADMIN_DEFAULT_PASSWORD: xxxx

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin-ns
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: ZmxleGRvYzk5