version: "3.9"

# EXECUTE O COMANDO ABAIXO ANTES DE RODAR ESTE DOCKER COMPOSER
# docker network create bancos-net
# docker network create flexdoc-net 

# COMANDO PARA RODAR ESTE COMPOSE
# docker-compose up -d --force-recreate

services:
  
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - "../volumes/mongodb:/bitnami/mongodb"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: flexdoc99
      MONGODB_DATABASE: test
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - 17000:8081
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: flexdoc99
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    restart: unless-stopped
    networks:
      - bancos-net
      - flexdoc-net

networks:
  bancos-net:
    external: true
  flexdoc-net:
    external: true
      
